//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open_Source_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorialTable
    {
        public int Id { get; set; }
        public string Difficulty { get; set; }
        public string Time { get; set; }
        public string Programming_Language { get; set; }
        public string Summary { get; set; }
        public string Outcomes { get; set; }
        public string BodyHtml { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string ShortSummary { get; set; }
        public string CodeSources { get; set; }
        public string TopicName { get; set; }
    }
}
